name: 每日執行 EveryPy 腳本

on:
  schedule:
    # 在 UTC 時間 22:50 執行，這對應台灣時間 (UTC+8) 的早上 6:50
    - cron: '50 22 * * *'
  workflow_dispatch: # 允許從 GitHub Actions 頁面手動觸發此流程，方便測試

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 簽出程式碼 (Checkout repository)
        uses: actions/checkout@v4

      - name: 設定 Python 環境 (Set up Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安裝依賴套件 (Install dependencies)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 執行 everypy.py 腳本 (Run EveryPy script)
        env:
          # 從 GitHub Secrets 讀取環境變數
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
          TELETHON_SESSION: ${{ secrets.TELETHON_SESSION }}
        run: |
          # 我們將 session 檔案的內容存在 Secret 中，並在執行前還原它
          echo "$TELETHON_SESSION" | base64 --decode > anon.session
          python everypy.py

      - name: 提交並推送 posts.json 的變更 (Commit and push changes)
        run: |
          # 設定 git 使用者資訊
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # 將變更加入到暫存區
          git add posts.json
          # 檢查是否有實際變更，如果有的話才執行 commit 和 push
          if ! git diff --staged --quiet; then
            git commit -m "每日自動更新文章 (Automated daily post update)"
            git push
          fi
